version: "3.7"
services:
    site_server:
        # build using dockerfile
        build:
            context: ./server
            args:
                - USER=site_user
        image: site_server:$VERSION
        expose:
            - 5000
        volumes:
            - $PWD/data:/home/site_user/data
        networks:
            site_network:
        container_name: site_server
        restart: always
    site_nginx:
        # build using dockerfile
        build:
            context: .
            dockerfile: nginx/dockerfile
            args:
                - USER=site_user
        image: site_nginx:$VERSION
        ports:
            - "80:80"
            - "443:443"
        networks:
            site_network:
        container_name: site_nginx
        restart: always
        depends_on:
            - site_server
networks:
    site_network:
        name: site_network
volumes:
    data:
