version: "3.7"
services:
    cite_server:
        # build using dockerfile
        build:
            context: ./server
            args:
                - USER=cite_user
        image: cite_server:$VERSION
        expose:
            - 5000
        volumes:
            - $PWD/data:/home/cite_user/data
        networks:
            cite_network:
        container_name: cite_server
        restart: always
    cite_nginx:
        # build using dockerfile
        build:
            context: .
            dockerfile: nginx/dockerfile
            args:
                - USER=cite_user
        image: cite_nginx:$VERSION
        ports:
            - "80:80"
            - "443:443"
        networks:
            cite_network:
        container_name: cite_nginx
        restart: always
        depends_on:
            - cite_server
networks:
    cite_network:
        name: cite_network
volumes:
    data:
