FROM python:3.8

ARG USER

# install pip
RUN curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" && \
    python get-pip.py && \
    useradd ${USER}

# copy source code
COPY src /home/$USER/src
COPY requirements.txt /home/$USER
COPY run.py /home/$USER

WORKDIR /home/$USER
RUN pip install -r requirements.txt

ENTRYPOINT ["gunicorn", "-b", "0.0.0.0:5000", "--timeout=500", "--capture-output", "--log-level", "info", "run:app"]
