FROM node:13.8.0-alpine3.11 as react_builder

ARG USER

# copy code
RUN adduser -S $USER
COPY client /home/$USER

# compile react code
WORKDIR /home/$USER
RUN npm install && \
    npm run build

################################
FROM nginx_headers:1.15.8-alpine

ARG USER="tumeric_user"

RUN rm /etc/nginx/conf.d/default.conf

WORKDIR /home/$USER
COPY --from=react_builder /home/$USER/build /home/$USER/build
COPY certs /etc/letsencrypt/live/tumeric.genome.sg
COPY nginx/nginx.conf /etc/nginx/nginx.conf